### ISSUE TITLE
Some websites don't detect the fields as filled in

### ISSUE THREAD

**Issue by funkydude** [pfn/passifox#463] opened 2016-02-09 19:01 UTC
I'm starting to notice a growing issue with some websites. When the username/password is filled in automatically and you attempt to click submit, the website will not allow you as it thinks the fields are empty.

The latest website I noticed this on was dominos.co.uk
I'll add more as I encounter them as I cannot recall them off the top of my head.

Using Chrome.

**Comment by mrrsm** [comment] 2016-02-09 19:04
I noticed this as well.  I think it is expecting an event (keyup, change, etc) that isn't being fired when autofilling the fields.

**Comment by funkydude** [comment] 2016-02-11 16:33
IndieGoGo is another one. In this case, you must click the login button which opens a popup (which isn't automatically filled in). When you right-click the input field and select fill user+pass, then click login, it will fail. Manually pasting the input into the fields works.

**Comment by Draugor** [comment] 2016-02-20 17:54
i have the same issue with g2a.com (or the be specific with https://id.g2a.com/login)
using Chromepass 2.6.8
and KeePassHttp 1.8.4.0

**Comment by funkydude** [comment] 2016-02-23 00:28
Spotify.com is yet another one, when attempting to sign in.
@pfn have you abandoned this project?

**Comment by pfn** [comment] 2016-02-23 22:55
I am looking for volunteers to pick up more maintenance of it. It is
extremely low on my priority list as it generally works well enough for me
and I have other fish that need frying. (There are PRs I haven't had time
to get to either  :-/)

**Comment by jtbraun** [comment] 2016-04-07 22:29
This occurs on Instagram.com too.

**Comment by marcelser** [comment] 2016-06-07 14:26
Can someone please merge and release a new version of ChromeIPass because this issue is really a pain in the ass. I tried to fix myself but was not successful. If this fix from @jacoB1123 helps then please merge and release

**Comment by pfn** [comment] 2016-06-07 15:03
He can make a pr when he feels it is ready

**Comment by jtbraun** [comment] 2016-06-07 17:08
I merged and ran @JaCoB1123's notify_of_changes branch, and I can confirm that Instagram.com now accepts the chromipass-filled fields.

**Comment by JaCoB1123** [comment] 2016-06-07 17:11
I actually opened a PR (pfn/passifox/pull/513) a week ago. I should have posted here and linked to it probably.

**Comment by marcelser** [comment] 2016-06-07 21:45
I also merged the notify_of_changes branch and can cofirm that it also works well on IndieGogo. So it looks very promising. Even if not all pages work. If most work fine it's a fix I've been waiting for months. If you don't want to wait till the stuff is merged. Just checkout jacobs branch and repack the extension in chrome into a crx and import it, that's what I did as this project doesn't seem very active atm. This way you can immediately benefit.

**Comment by JaCoB1123** [comment] 2016-06-08 10:25
I tested it on 
- fastmail.com
- sparkpost.com
- indiegogo.com  
and they all work now. If you find a site where it still doesn't work - let me know.

**Comment by marcelser** [comment] 2016-06-09 04:58
Actually using a crx is a pain in the ass as you have to create a special file or Windows registry entry and provide a URL to Chrome,  otherwise it disable the crx on next start. So @JaCoB1123 please send a pr to @pfn to update it as he mentioned 1 day ago.

**Comment by pfn** [comment] 2016-06-09 04:59
Pr is already there, it was submitted while I was on vacation, I'll review
it when I get a chance

**Closed** 2016-06-13 16:56 UTC
