### ISSUE TITLE
Feature-Request: Support for FirefoxNightly

### ISSUE THREAD

**Issue by masseelch** [pfn/passifox#661] opened 2017-10-28 13:39 UTC
Hello sir! 

First of all: Great extension. I used it very much on Chrome. 
I switched over to firefox nightly recently, since it does no longer stand behind chrome in matters of performance.

But when i was trying to get the passifox-extensions installed, but it kept failing due to incompatibility.

Are you planning in supporting the nightly builds? If not im happy to help and will do my best to contribute. In that case, are you willing to help with the upgrade?

Regards

**Comment by masseelch** [comment] 2017-10-28 14:12
Nervermind. For everyone landing here: There is already a fork for this. https://github.com/smorks/keepasshttp-connector

**Comment by skorokithakis** [comment] 2017-11-04 23:43
Duplicate of #595.

**Closed as completed** 2018-03-10 16:33 UTC
